# Generated by Django 4.2.7 on 2025-03-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="course-file"),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="course-file"),
        ),
    ]
