# Generated by Django 4.2.7 on 2025-03-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_course_file_alter_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
