# Generated by Django 4.2.7 on 2025-03-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_review_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantitem",
            name="file",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
