# Generated by Django 4.2.7 on 2025-04-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_variantitem_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantitem",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="course-file"),
        ),
    ]
